### ISSUE TITLE
Autocomplete gives different options than command-line elm-oracle

### ISSUE THREAD

**Issue by Dedoig** [edubkendo/atom-elm#13]
Just installed language-elm 1.0.3 ... Looks fabulous, thanks!

Autocomplete from atom seems to give inconsistent results as I type more input e.g.

![image](https://cloud.githubusercontent.com/assets/8269863/10238206/3d3e7498-6882-11e5-8f07-78e7898a2bc8.png)

vs. type another "f" (notice `Effects` missing in Atom above):

![image](https://cloud.githubusercontent.com/assets/8269863/10238220/72609552-6882-11e5-968f-9ffe4ddfb2a7.png)

And results differ from elm-oracle called from command line:

![image](https://cloud.githubusercontent.com/assets/8269863/10238235/9fbae12e-6882-11e5-914e-72753c908d48.png)

vs. command line (notice `foldp` missing in Atom above)

![image](https://cloud.githubusercontent.com/assets/8269863/10238251/c0fbc81c-6882-11e5-8e03-43495a30c6d5.png)

**Comment by brianegan** [comment]
Cool, thanks for the report! I'll check it out tomorrow :)

**Comment by brianegan** [comment]
Thanks again for writing in. I took a few minutes to look at this, and found there are actually two problems here:

  1. Atom-elm is giving different results than what you got got when you manually ran elm-oracle from the command line.
    - I've made a pull request that addresses this issue. Instead of passing in `Signal.fol` to elm-oracle, this plugin used to simply pass the `fol`. I've now corrected the plugin to pass the full `Signal.fol` so the suggestions are more context-aware and accurate!
  2. "Autocomplete from atom seems to give inconsistent results as I type more input e.g... Eff"
    - Unfortunately, even after correcting the first problem, elm-oracle doesn't seem to be returning very good suggestions for the situation you're talking about. It appears elm-oracle is optimized for suggesting methods over Libraries or modules. If you'd like to see that improved, you could consider filing a bug or helping by contributing a bit of code to the elm-oracle project  :)
