### ISSUE TITLE
Autocomplete is too intrusive

### ISSUE THREAD

**Issue by z5h** [edubkendo/atom-elm#14]
Anything typed immediately brings up autocomplete. 
I can't press enter while coding without hitting Esc first.

**Comment by brianegan** [comment]
Thanks for letting me know! And sorry to hear about the issue.

Do you find this same behavior happens when you use autocomplete in other languages, or simply when editing Elm files? I'm trying to determine if this is something that's gone wrong with this package or perhaps the autocomplete-plus package itself.

**Comment by damassi** [comment]
An example is when you start typing something like... 

```
update action model = 
  case action of 
```

...right after the space after of an autocomplete window listing every item appears. It should be limited to a appearing only after a few characters have been entered and parsed.

**Comment by damassi** [comment]
Another nice thing-to-have would be a setting option for enabling / disabling autocomplete.

**Comment by brianegan** [comment]
Cool, very constructive feedback. I'll make those two modifications!

**Comment by damassi** [comment]
One other setting that might be nice is a trigger sensitivity value -- input that defines a min number of characters to enter before autocomplete appears. Some people type so fast that only the longest words should be searched and offered.

**Comment by brianegan** [comment]
Makes sense. I'll add that to the list :0

**Comment by brianegan** [comment]
Thanks again for writing in! The options have been added to the plugin, and hopefully make it a better experience for all :)

**Comment by damassi** [comment]
Awesome, thanks so much! Would you be so kind as to publish to apm :)

**Comment by brianegan** [comment]
Unfortunately, I don't have the rights. @edubkendo, if you get a chance, could you please publish the package?

**Comment by edubkendo** [comment]
done!

**Comment by brianegan** [comment]
Perfect, thanks!

**Comment by damassi** [comment]
Thanks yall :+1:

**Comment by z5h** [comment]
Thanks everyone.
