### ISSUE TITLE
Having trouble setting up on Windows

### ISSUE THREAD

**Issue by jpierson** [edubkendo/atom-elm#16]
I'm having trouble completing step 5 in the readme.md.
> 5. Open up the language-elm settings in Atom

I'm new to both Atom and Elm and I'm not sure whether my inability to find the settings is due to a missed step, a difference in platform or just something else I'm overlooking.

**Comment by brianegan** [comment]
Hey, thanks for writing in! I'll take a bit of time tomorrow to write up some instructions and add them to the README :)
