### ISSUE TITLE
Linux Mint on 1.0.3 gets stuck in loop

### ISSUE THREAD

**Issue by NicholasGW** [edubkendo/atom-elm#17]
Noticed this error and found the cause, but wasn't sure of the best fix. In provider.js:

          const exactDependenciesPath = path ? `${path}${sep}elm-stuff${sep}exact-dependencies.json` : '';

          if (path) {
            try {
              const stats = statSync(exactDependenciesPath);
              return path;
            } catch(e) 

The statSync will fail on a"valid" path because there is no leading /, as it has been split i.e. it tries to look for home/nick/dev/elm-charts/ as opposed to /home/nick/dev/elm-charts.

If you fix this by adding ${sep} to the beginning of the exactDependenciesPath, it still errors because here the cwd is again set without a / :

      const filePath = editor.getPath();
      const elmProjectPath = findClosestElmProjectPath(filePath.split(sep).slice(0, -1));
      const executablePath = atom.config.get('language-elm.elmOraclePath');
      const options = {
        cwd: elmProjectPath,
        env: process.env
      };

I fixed that by setting the cwd to sep + elmProjectPath, but I assumed that might not be cross OS enough so I thought I'd just make a bug :).

**Comment by brianegan** [comment]
Thanks for the heads up! I was wondering if that might cause problems for others, but seemed to be working on my Mac. I'll give the fix a shot and see how it goes :)

**Comment by brianegan** [comment]
Hey NicholasGW! I got a few minutes to look at this problem and coded up a solution. We'll try to publish an updated version soon which fixes the problem!

**Comment by NicholasGW** [comment]
Awesome @brianegan , thanks! I'll be happy to test when the time comes :).
