### ISSUE TITLE
Markdown in tooltip not processed 

### ISSUE THREAD

**Issue by Fresheyeball** [edubkendo/atom-elm#23]
![screen shot 2015-10-15 at 2 27 16 pm](https://cloud.githubusercontent.com/assets/609279/10526608/34e07766-7349-11e5-8673-08420ed90623.png)

**Comment by brianegan** [comment]
Hey, thanks for filing this report! Unfortunately, there's no way around this :( It's a hard limit in the atom autocomplete plus module that only text is allowed in this area. If you try to pass HTML, it will actually break the suggestions.

Here's the line in the atom autocomplete plus code where the limit comes from. I'm not sure if the authors would be open to allowing html in there, given some of the security risks that come along with it, but it's something you ask for:

https://github.com/atom/autocomplete-plus/blob/38b307841a4ab9da54612fa7cd3a9b8ccd6244ec/lib/suggestion-list-element.coffee#L106

**Comment by Fresheyeball** [comment]
Hmmm, sanitizing HTML for security is kind of a known thing. Id think they would just add that layer of assurance and let HTML in.
