### ISSUE TITLE
Types get truncated

### ISSUE THREAD

**Issue by Fresheyeball** [edubkendo/atom-elm#24]
In the tooltip, it would be nice to always see the entire type (no matter how long) 
![screen shot 2015-10-15 at 2 28 02 pm](https://cloud.githubusercontent.com/assets/609279/10526623/47de2d04-7349-11e5-98ed-72c90b65477c.png)

**Comment by brianegan** [comment]
Hey, thanks for writing it! That's a default of the atom autocomplete plus plugin, and I didn't want to modify those defaults from within this plugin just yet. However, after seeing your screenshot, it makes me realize I'd gotten used to my own configuration which shows much more of the signature, and how much nicer it is. Therefore, I've pushed up a change that should make it easier to read the descriptions & signatures :)

**Comment by Fresheyeball** [comment]
Nice!
