### ISSUE TITLE
Support symbols

### ISSUE THREAD

**Issue by thSoft** [edubkendo/atom-elm#26]
It would be great if top-level declarations appeared as symbols in order to make "go to symbol" work.

**Comment by splodingsocks** [comment]
I've been looking around, trying to figure out how to go about this, and I haven't made any headway so far. Anyone have any tips?

**Comment by splodingsocks** [comment]
@thSoft Looks like this plugin supports Elm symbols : https://atom.io/packages/goto I just installed and tested it. Atom's built-in provider uses ctags, and I'm guessing there isn't default support in ctags for Elm. Goto uses the syntax definitions to generate the symbols, so it appears to work well.

**Comment by thSoft** [comment]
Cool! Then could you please add a note about this in the readme?
