### ISSUE TITLE
Working offline crashes atom-elm

### ISSUE THREAD

**Issue by baer** [edubkendo/atom-elm#29]
Hello!
I noticed that working offline crashes the elm-oracle. I don't have time to look into this until after the holidays but I'm assuming that this is as simple as returning an empty string somewhere.

Thanks for the awesome package!

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.2
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.3.0

### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /Users/ebaer/.atom/packages/language-elm/lib/provider.js:256

Error: No elm-oracle suggestions
    at noOutputFromOracleError (/Users/ebaer/.atom/packages/language-elm/lib/provider.js:227:10)
    at parseOutput (/Users/ebaer/.atom/packages/language-elm/lib/provider.js:256:11)
    at provideSuggestions (/Users/ebaer/.atom/packages/language-elm/lib/provider.js:59:15)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
  2x -3:01.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:00.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:00.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:00.9.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -3:00.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:55.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:46.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:46.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:11.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:03.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:03.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.5.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:03.5.0 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ],
    "useReactEditor": true,
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
atom-handlebars, v1.3.0
autocomplete-paths, v1.0.2
docblockr, v0.7.3
file-icons, v1.6.13
language-elm, v1.3.0
minimap, v4.18.2
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-selection, v4.3.1
react, v0.12.10
sync-settings, v0.6.0
tabs-to-spaces, v1.0.1
theme-switcher, v1.1.0

# Dev
No dev packages
```

**Comment by brianegan** [comment]
Ah, interesting finding! I'll check it out next week :)

**Comment by brianegan** [comment]
Hey hey :) 

Unfortunately, if you're offline, you won't be able to get any elm oracle suggestions and I'd like to keep this error present to help catch other bugs unrelated to being offline. That said, in this case, this error message is supposed to be helpful, but it's just annoying :)

I looked into this and I've made the messages far less noisy. I still think it's a good idea to inform users who are new to Atom-elm that they need to run `elm package install` in their project folders to get the most out of atom elm (and to compile their projects!). But this should no longer throw big red errors in your face any more. You'll see one (hopefully) helpful warning message that you aren't getting suggestions and what you can do to remedy the problem, and after that the plugin should stay silent.

The changes should be deployed sometime soon. Thanks for writing in :)
