### ISSUE TITLE
More instructions in readme?

### ISSUE THREAD

**Issue by evancz** [edubkendo/atom-elm#34]
I sat with @christinecha as she got Elm installed and started playing around with it for the first time. It was weirdly difficult to get syntax highlighting working for Elm in Atom though.

  1. She installed via `npm` but the highlighting did not work.
  2. She googled around to figure out where the heck `apm` is in the editor itself.
  3. When she finally found it, it said that `language-elm` was already installed.
  4. She uninstalled, and reinstalled through the UI.

Then it worked. I don't really know why it was that way, but I feel like having more comprehensive instructions in the README could save people a bunch of time. Maybe just saying how to get to the package search thing in the editor? Not really sure!

**Comment by brianegan** [comment]
Ouch. Not a good first time experience. Thanks for the feedback! 

I'll write up some instructions for the README :)

**Comment by brianegan** [comment]
@evancz Hey there, I put together some instructions! When you get a chance, could you please give them a gander and let me know if they solve the issue you are describing?

Link to updated Readme: 
https://github.com/edubkendo/atom-elm/blob/better-instructions/README.md

**Comment by christinecha** [comment]
Looks good to me! :)

Did we figure out why it wasn't *fully* installing when I ran "apm install
language-elm", though?

On Mon, Feb 29, 2016 at 6:10 PM, Brian Egan <notifications@github.com>
wrote:

> @evancz <https://github.com/evancz> Hey there, I put together some
> instructions! When you get a chance, could you please give them a gander
> and let me know if they solve the issue you are describing?
>
> Link to updated Readme:
> https://github.com/edubkendo/atom-elm/blob/better-instructions/README.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edubkendo/atom-elm/issues/34#issuecomment-190441863>.
>



-- 
Christine Cha

DEVELOPER + DESIGNER  //  *CHRISTINECHA.COM* <http://christinecha.com>
NYC LEAN IN CHAPTER LEADER  //  *NYCLEANIN.COM <http://nycleanin.com>*

NEW PROJECTS --
*CIRCLEMATCH <http://christinecha.github.io/circlematch/>: *a minimalistic
twist on the classic 8-piece slide puzzle.

**Comment by brianegan** [comment]
@christinecha Yay! Glad it fixed part of the problem. And sorry, totally my bad, should have cc'd you as well on that comment as well. With regards to `apm` failing, I'd have to say: I really have no idea :(

Would you be willing to try installing it again via apm? Does it fail every time for you? Did it give any additional feedback, or just say `Installing language-elm to... (check mark)`?

My general debugging strategy in this case would be to 1. reproduce the error, or 2. get some detailed logs from `apm` and look through them to see where the installation failed. Unfortunately, I haven't been able to reproduce the error, and I don't see a way to get any logs out of `apm`. Therefore, I don't feel I have the tools to say what could have gone wrong. If you can reproduce consistently and / or provide logs, I'd be happy to dig in further!
