### ISSUE TITLE
Uncaught Error: No elm-oracle suggestions

### ISSUE THREAD

**Issue by rebelwarrior** [edubkendo/atom-elm#38]
Suddenly got a ton of these. No clue what changed.

**Comment by rebelwarrior** [comment]
Updating elm-oracle `npm -g install elm-oracle` fixed it.

**Comment by visq** [comment]
Why did you close this issue?
Fresh install of both elm and atom on Win7 today, ran into the same problem.
I do not have npm installed on this machine (as far as I can tell).
```
/C:/Users/<me>/.atom/packages/language-elm/lib/elmOracle.js:144
Hide Stack Trace
Error: No elm-oracle suggestions
    at parseOutput (C:/Users/<me>/.atom/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (C:/Users/<me>/.atom/packages/language-elm/lib/elmOracle.js:27:27)
    at ChildProcess.<anonymous> (C:/Users/<me>/.atom/packages/language-elm/lib/elmOracle.js:62:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by edubkendo** [comment]
https://github.com/edubkendo/atom-elm#autocomplete

elm-oracle, which this package depends on to provide autocomplete suggestions, requires being installed with npm @visq

**Comment by visq** [comment]
@edubkendo 
Ok, thanks for the hint, but why is this necessary (no npm installed here) and how should I know?
Anyway, I decided that atom is too unstable for me to use, so no worries.

**Comment by edubkendo** [comment]
Well, this package (like most good autocompletion packages for text editors) gets its autocompletions from an external tool. In this case, that tool is elm-oracle, which is installed as a node package via npm. 

We explain this in the documentation, under the section I linked in my previous reply. If you have any suggestions for how we could make that documentation more clear, though, I'm happy to see if we can improve it. Thanks.

**Comment by visq** [comment]
@edubkendo 
Sure, it's perfectly fine to rely on a third-party package.
The issue is that it is not possible to use atom-elm out of the box (i.e. installed via atom package manager) without installing elm-oracle, because a window is popping up showing error messages. 
You could improve the documentation by stating early on that it is mandatory to install elm-oracle via npm, and that atom-elm will not work if elm-oracle is missing.

**Comment by gkutiel** [comment]
Happens also in Ubuntu 16.04, elm-oracle 1.1.0, npm 3.9.3

```
apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11+
git 2.7.4
```

```
atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.
```

**The elm-oracle works fine from command line**

**Comment by gkutiel** [comment]
The problem was in the config.cson file

was

```
elmOraclePath: '''
   /usr/bin/elm-oracle
'''

```

should be 
`elmOraclePath: "/usr/bin/elm-oracle"`
