### ISSUE TITLE
Elm 0.17 module syntax

### ISSUE THREAD

**Issue by tdheff** [edubkendo/atom-elm#41]
In 0.17 the module syntax has changed:

<table>
  <tr>
    <th>feature</th>
    <th>0.16</th>
    <th>0.17</th>
  </tr>

  <tr>
    <td>module declaration</td>
    <td><pre lang="elm">module Queue (..) where</pre></td>
    <td><pre lang="elm">module Queue exposing (..)</pre></td>
  </tr>
</table>

The current syntax highlighting does not support this.

**Comment by domenkozar** [comment]
fixed in https://github.com/edubkendo/atom-elm/commit/77f2f11edf665a139bef82e675a877954e567c53
